#!/bin/sh

msg() { printf "\033[1;34m[sinit]\033[0m %s\n" "$@"; }

export PATH=/usr/bin

msg "Starting Ataraxia Linux"
dmesg -n 1
ctraltdel -s

openrc sysinit
openrc boot

single="0"
for arg in $(cat /proc/cmdline);do
	case "$arg" in
		single=*)      single="${arg#*=}" ;;
	esac
done

if [ "$single" = "1" ]; then
	msg "Going single-user..."
	setsid cttyhack /usr/bin/mksh
	reboot
else
	msg "Goint mult-user..."
	openrc default
fi
