#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-alsa}"

start() {
	echo "Starting ${SVNAME}..."
	if [ ! -f "/var/lib/alsa/asound.state" ]; then
		mkdir -p /var/lib/alsa/
		alsactl restore
		alsactl store
	fi
	alsactl restore
	perpctl -b /etc/perp p ${SVNAME}
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			alsactl store
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
