#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-bluetoothd}"

start() {
	echo "Starting ${SVNAME}..."
	if ! perpok -u3 dbus; then
		exit 1
	fi

	exec /usr/lib/bluetooth/bluetoothd -n
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
