#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-consolekit}"

start() {
	echo "Starting ${SVNAME}..."
	if ! perpok -b /etc/perp -u3 dbus; then
		exit 1
	fi

	exec /usr/bin/console-kit-daemon --no-daemon
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
