#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-dbus}"

start() {
	echo "Starting ${SVNAME}..."
	[ ! -d /run/dbus ] && mkdir -p /run/dbus

	dbus-uuidgen --ensure
	exec /usr/bin/dbus-daemon --system --nofork --nopidfile
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
