#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-distcc}"

start() {
	echo "Starting ${SVNAME}..."
	[ -r /etc/conf.d/distccd ] && . /etc/conf.d/distccd
	exec /usr/bin/distccd --no-detach --daemon $DISTCC_ARGS
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
