#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-dnsmasq}"

start() {
	echo "Starting ${SVNAME}..."
	mkdir -p /var/lib/misc

	exec /usr/bin/dnsmasq -k -u dnsmasq -g dnsmasq
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
