#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-dropbear}"

start() {
	echo "Starting ${SVNAME}..."
	[ -r "/etc/conf.d/dropbear" ] && . /etc/conf.d/dropbear
	exec /usr/bin/dropbear ${OPTS:=-F -R}
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
