#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-gdm}"

start() {
	echo "Starting ${SVNAME}..."
	if ! perpok -b /etc/perp -u3 dbus; then
		exit 1
	fi

	if ! perpok -b /etc/perp -u3 accounts-daemon; then
		exit 1
	fi

	[ ! -d /run/gdm ] && mkdir -m0711 -p /run/gdm && chown root:gdm /run/gdm
	exec gdm
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
