#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-hostapd}"

start() {
	echo "Starting ${SVNAME}..."
	exec hostapd -s /etc/hostapd/hostapd.conf
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
