#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-ip6tables}"

start() {
	echo "Starting ${SVNAME}..."
	[ ! -e /etc/iptables/ip6tables.rules ] && perpctl d ${SVNAME}
	ip6tables-restore /etc/iptables/ip6tables.rules || perpctl d ${SVNAME}
	perpctl p ${SVNAME}
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			/usr/lib/iptables-flush -6
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
