#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-iptables}"

start() {
	echo "Starting ${SVNAME}..."
	[ ! -e /etc/iptables/iptables.rules ] && exit 0
	iptables-restore /etc/iptables/iptables.rules || exit 1
	exec yes
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			/usr/lib/iptables-flush
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
