#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-krb5kdc}"

start() {
	echo "Starting ${SVNAME}..."
	exec /usr/bin/krb5kdc -n
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
