#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-lightdm}"

start() {
	echo "Starting ${SVNAME}..."
	if ! perpok -b /etc/perp -u3 dbus; then
		exit 1
	fi

	[ ! -d /run/lightdm ] && install -d -m0711 -olightdm -glightdm /run/lightdm
	exec /usr/bin/lightdm
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
