#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-networkmanager}"

start() {
	echo "Starting ${SVNAME}..."
	if ! perpok -u3 dbus; then
		exit 1
	fi

	if [ ! -d /run/NetworkManager ]; then
		install -d -o root -g root -m 755 /run/NetworkManager
	fi
	exec /usr/bin/NetworkManager -n
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
