#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-nfs}"

start() {
	echo "Starting ${SVNAME}..."
	if ! perpok -u3 rpc.statd; then
		exit 1
	fi

	if [ -e /etc/conf.d/nfs ]; then
		. /etc/conf.d/nfs
	fi

	if ! mountpoint -q /var/lib/nfs/rpc_pipefs; then
		mount -t rpc_pipefs rpc_pipefs /var/lib/nfs/rpc_pipefs -o defaults || exit 1
	fi
	if ! mountpoint -q /proc/fs/nfsd; then
		mount -t nfsd nfsd /proc/fs/nfsd || exit 1
	fi

	exportfs -ra > /dev/null || exit 1
	rpc.nfsd -- ${PROCESSES:=4} || exit 1
	sm-notify

	exec rpc.mountd --foreground
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."

			exportfs -ua
			rpc.nfsd -- 0
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
