#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-nftables}"

start() {
	echo "Starting ${SVNAME}..."
	nft -f /etc/nftables.conf
	exec yes
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			nft flush ruleset
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
