#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-nftables}"

start() {
	echo "Starting ${SVNAME}..."
	[ ! -r /etc/nftables.conf ] && perpctl -b /etc/perp d ${SVNAME}
	nft -f /etc/nftables.conf || perpctl -b /etc/perp d ${SVNAME}
	perpctl -b /etc/perp p ${SVNAME}
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			nft flush ruleset
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
