#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-nmbd}"

start() {
	echo "Starting ${SVNAME}..."
	[ ! -d /run/samba ] && mkdir -p /run/samba

	exec /usr/bin/nmbd -F -S
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
