#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-ntpd}"

start() {
	echo "Starting ${SVNAME}..."
	[ -r /etc/conf.d/ntpd ] && . /etc/conf.d/ntpd

	exec ntpd ${NTPD_OPTS:--N -p pool.ntp.org}
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
