#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-redis}"

start() {
	echo "Starting ${SVNAME}..."
	[ ! -d /run/redis ] && install -d -m0750 -o redis -g redis /run/redis
	exec runtool -u redis /usr/bin/redis-server /etc/redis.conf
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
