#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-rsyncd}"

start() {
	set -e
	[ ! -e /etc/rsyncd.conf ] && exit 1

	echo "Starting ${SVNAME}..."
	exec rsync --daemon --no-detach
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
