#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-sshd}"

create_keys() {
	if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
		ssh-keygen -q -t rsa -b 2048 -N "" -f /etc/ssh/ssh_host_rsa_key
	fi
	if [ ! -f /etc/ssh/ssh_host_dsa_key ]; then
		ssh-keygen -q -t dsa -N "" -f /etc/ssh/ssh_host_dsa_key
	fi
	if [ ! -f /etc/ssh/ssh_host_ecdsa_key ]; then
		ssh-keygen -q -t ecdsa -b 521 -N "" -f /etc/ssh/ssh_host_ecdsa_key
	fi
	if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
		ssh-keygen -q -t ed25519 -N "" -f /etc/ssh/ssh_host_ed25519_key
	fi
}

start() {
	echo "Starting ${SVNAME}..."
	create_keys

	exec /usr/bin/sshd -De
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
