#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-transmission}"

start() {
	echo "Starting ${SVNAME}..."
	exec runtool -u transmission /usr/bin/transmission-daemon -f --log-error
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
