#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-tty1}"

start() {
	echo "Starting ${SVNAME}..."
	exec setsid getty 38400 tty1 linux
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
