#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-ttyAMA0}"

start() {
	echo "Starting ${SVNAME}..."
	exec getty -L ttyS0 115200 vt100
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
