#!/bin/sh
#

exec 2>&1

TARGET="$1"
BASENAME="$(basename $PWD)"
SVNAME="$BASENAME"
INTERFACE="$(echo $BASENAME | cut -d - -f 2)"

start() {
	echo "Starting ${SVNAME}..."
	if [ "$INTERFACE" != "${SVNAME//udhcpc-/}" ]; then
		perpctl -b /etc/perp d ${SVNAME}
	fi

	ip link set ${INTERFACE} up

	if [ -e "/etc/conf.d/network.${INTERFACE}" ]; then
		. /etc/conf.d/network.${INTERFACE}
	fi

	if [ "$IPV6" = "true" ]; then
		UDHCPC="udhcpc6"
	else
		UDHCPC="udhcpc"
	fi

	exec $UDHCPC $DHCPC_OPTS -f -i ${INTERFACE} -p "/run/udhcpc-$INTERFACE.pid"
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			ip link set ${INTERFACE} down
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
