#!/bin/sh
#

exec 2>&1

TARGET="$1"
INTERFACE="$(echo $PWD | cut -d - -f 2)"
if [ ! -z "$INTERFACE" ]; then
	SVNAME="${2:-udhcpc-$INTERFACE}"
else
	SVNAME="${2:-udhcpc}"
fi

start() {
	echo "Starting ${SVNAME}..."
	if [ -z "$INTERFACE" ]; then
		perpctl -b /etc/perp d ${SVNAME}
	fi

	if perpok -b /etc/perp -u3 networkmanager; then
		perpctl -b /etc/perp d ${SVNAME}
	fi

	ip link set ${INTERFACE} up

	if [ -e "/etc/conf.d/network.${INTERFACE}" ]; then
		. /etc/conf.d/network.${INTERFACE}
	fi

	if [ "$IPV6" = "true" ]; then
		UDHCPC="udhcpc6"
	else
		UDHCPC="udhcpc"
	fi

	exec $UDHCPC $DHCPC_OPTS -f -i ${INTERFACE} -p "/run/$SVNAME.pid"
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			kill -9 "$(cat /run/$SVNAME.pid)"

			ip link set ${INTERFACE} down
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
