#!/bin/sh
#

exec 2>&1

TARGET="$1"
INTERFACE="$(echo $PWD | cut -d - -f 2)"
SVNAME="${2:-udhcpc-$INTERFACE}"

start() {
	echo "Starting ${SVNAME}..."
	if [ -z "$INTERFACE" ]; then
		perpctl d ${SVNAME}
	fi

	if perpok -u3 networkmanager; then
		perpctl d ${SVNAME}
	fi

	ip link set ${INTERFACE} up

	exec udhcpc -f -i ${INTERFACE} -p "/run/$SVNAME.pid"
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			kill -9 "$(cat /run/$SVNAME.pid)"

			ip link set ${INTERFACE} down
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
