#!/bin/sh
#

exec 2>&1

TARGET="$1"
SVNAME="${2:-uuid}"

start() {
	echo "Starting ${SVNAME}..."
	[ ! -d /run/uuidd ] && mkdir -p /run/uuidd
	chown _uuidd:_uuidd /run/uuidd

	perpctl -b /etc/perp p ${SVNAME}
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
