#!/bin/sh
#

exec 2>&1

TARGET="$1"
INTERFACE="$(echo $PWD | cut -d - -f 2)"
if [ ! -z "$INTERFACE" ]; then
	SVNAME="${2:-wpa_supplicant-$INTERFACE}"
else
	SVNAME="${2:-wpa_supplicant}"
fi

start() {
	CONFIG="/etc/wpa_supplicant/wpa_supplicant.conf"

	echo "Starting ${SVNAME}..."
	if [ -z "$INTERFACE" ]; then
		perpctl -b /etc/perp d ${SVNAME}
	fi

	if [ ! -f "$CONFIG" ]; then
		perpctl -b /etc/perp d ${SVNAME}
	fi

	if perpok -b /etc/perp -u3 networkmanager; then
		perpctl -b /etc/perp d ${SVNAME}
	fi

	ip link set ${INTERFACE} up

	if [ -e "/etc/conf.d/network.${INTERFACE}" ]; then
		. /etc/conf.d/network.${INTERFACE}
	fi

	if [ "$IPV6" = "true" ]; then
		UDHCPC="udhcpc6"
	else
		UDHCPC="udhcpc"
	fi

	exec \
		wpa_supplicant $WPA_OPTS -B -i${IFUP} -c$CONFIG -P/run/wpa-$INTERFACE.pid -d \
		$UDHCPC $DHCPC_OPTS -f -i ${INTERFACE} -p "/run/udhcpc-$INTERFACE.pid"
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			kill -9 "$(cat /run/udhcpc-$INTERFACE.pid)"
			kill -9 "$(cat /run/wpa-$INTERFACE.pid)"

			ip link set ${INTERFACE} down
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
