#!/bin/sh
#

exec 2>&1

TARGET="$1"
INTERFACE="$(echo $PWD | cut -d - -f 2)"
SVNAME="${2:-wpa_supplicant-$INTERFACE}"

start() {
	CONFIG="/etc/wpa_supplicant/wpa_supplicant.conf"

	echo "Starting ${SVNAME}..."
	if [ -z "$INTERFACE" ]; then
		perpctl d ${SVNAME}
	fi

	if [ ! -f "$CONFIG" ]; then
		perpctl d ${SVNAME}
	fi

	if perpok -u3 networkmanager; then
		perpctl d ${SVNAME}
	fi

	ip link set ${INTERFACE} up

	if [ -e /etc/conf.d/wpa_supplicant ]; then
		. /etc/conf.d/wpa_supplicant
	fi

	exec \
		wpa_supplicant $WPA_OPTS -B -i${IFUP} -c$CONFIG -P/run/wpa-$INTERFACE.pid -d \
		udhcpc -f -i ${INTERFACE} -p "/run/udhcpc-$INTERFACE.pid"
}

reset() {
	case $3 in
		exit)
			echo "Stopping ${SVNAME}..."
			kill -9 "$(cat /run/udhcpc-$INTERFACE.pid)"
			kill -9 "$(cat /run/wpa-$INTERFACE.pid)"

			ip link set ${INTERFACE} down
			;;
		signal)
			echo "Killing ${SVNAME}..."
			;;
		*)
			echo "Stopping ${SVNAME}..."
			;;
	esac
}

eval ${TARGET} "$@"
