#!/bin/sh

DSSKEY=/etc/dropbear/dropbear_dss_host_key
RSAKEY=/etc/dropbear/dropbear_rsa_host_key

if [ ! -r "$DSSKEY" ]; then
	dropbearkey -t dss -f "$DSSKEY" >/dev/null 2>&1
fi
if [ ! -r "$RSAKEY" ]; then
	dropbearkey -t rsa -f "$RSAKEY" >/dev/null 2>&1
fi

exec dropbear
