#!/usr/bin/sh
#

for i in /usr/bin/fixfiles /usr/bin/setenforce; do
	test -x "$i" && continue
	echo "$i is missing in the system."
	echo "Please add \"selinux=0\" in the kernel command line to disable SELinux."
	exit 1
done

if [ -f "/.autorelabel" ]; then
	echo "SELinux: /.autorelabel placed, filesystem will be relabeled..."
	setenforce 0
	fixfiles -F -f relabel
	rm -f /.autorelabel
	echo "Relabel done, rebooting the system."
	systemctl reboot
fi

exit 0

