#!/bin/sh

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"

if [ -e /run/runit/reboot ]; then
	chmod 100 /run/runit/reboot
fi

sv force-stop /var/service/*
sv exit /var/service/*

stty onlcr 0>&1

ifdown -a

hwclock --systohc --utc

if egrep -q -m 1 '(usr|grp)quota' /etc/fstab
then
	if type quotaoff > /dev/null
	then
		quotaoff -va
	fi
fi

( umask 077; bytes=$(cat /proc/sys/kernel/random/poolsize) || bytes=512; dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=$bytes >/dev/null 2>&1 )

halt -w

if [ "$live" != "1" ]; then
	if [ -x /usr/bin/vgchange ]; then
		vgchange --ignorelockingfailure -a n >/dev/null 2>&1
	fi
fi

udevadm control --exit

pkill --inverse -s0,1 -TERM
sleep 1
pkill --inverse -s0,1 -KILL

swapoff -a

umount -r -a -t nosysfs,noproc,nodevtmpfs,notmpfs

mount -o remount,ro /

sync
