#!/bin/sh

# pedophile
CPDIR="$1"

find $CPDIR -name \*.packlist -delete
find $CPDIR -name \*.pod -delete
find $CPDIR -name \*.la -delete
rm -rf $CPDIR/{,usr/}{,local/}{,share/}{doc,man,info,locale} $CPDIR/{,usr/}{,/local}{,/share},opt/*}/{man,info} $CPDIR/{,usr/}{,local/}{,share/}{doc,gtk-doc} $CPDIR/opt/*/{doc,gtk-doc} $CPDIR/{,usr/}lib/locale
rm -rf $CPDIR/{,usr/}lib/charset.alias

find $CPDIR -type f | xargs file 2>/dev/null | grep "LSB executable"       | cut -f 1 -d : | xargs strip --strip-all			2>/dev/null || true
find $CPDIR -type f | xargs file 2>/dev/null | grep "shared object"        | cut -f 1 -d : | xargs strip --strip-unneeded		2>/dev/null || true
find $CPDIR -type f | xargs file 2>/dev/null | grep "current ar archive"   | cut -f 1 -d : | xargs strip --strip-debug			2>/dev/null || true
