#!/bin/sh

# pedophile
CPDIR="$1"

find $CPDIR -name \*.packlist -delete
find $CPDIR -name \*.pod -delete
find $CPDIR -name \*.la -delete
rm -rf $CPDIR/{,usr/}{,local/}{,share/}{doc,man,info,locale} $CPDIR/{,usr/}{,/local}{,/share},opt/*}/{man,info} $CPDIR/{,usr/}{,local/}{,share/}{doc,gtk-doc} $CPDIR/opt/*/{doc,gtk-doc} $CPDIR/{,usr/}lib/locale
rm -rf $CPDIR/{,usr/}lib/charset.alias
