#!/bin/sh

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"

live="0"
for arg in $(cat /proc/cmdline);do
	case "$arg" in
		live=*)     live="${arg#*=}" ;;
	esac
done

stty onlcr

sv down /var/service/*

ifdown -v -a

hwclock -v --systohc --utc

if egrep -q -m 1 '(usr|grp)quota' /etc/fstab
then
	if type quotaoff > /dev/null
	then
		quotaoff -va
	fi
fi

( umask 077; bytes=$(cat /proc/sys/kernel/random/poolsize) || bytes=512; dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=$bytes >/dev/null 2>&1 )

if [ "$live" != "1" ]; then
	if [ -x /usr/bin/vgchange ]; then
		vgchange -v --ignorelockingfailure -a n
	fi
fi

udevadm control --exit

killall5 -s TERM
sleep 1
killall5 -s KILL

swapoff -v -a

umount -v -r -a -t nosysfs,noproc,nodevtmpfs,notmpfs

if [ "$live" != "1" ]; then
	mount -v -o remount,ro /
fi

sync

if [ "$live" != "1" ]; then
	if [ "$1" = "reboot" ]; then
		if command -v kexec >/dev/null; then
			kexec -e 2>/dev/null
		fi
	fi
fi

case "$1" in
	reboot)
		halt -r
		;;
	poweroff)
		halt -p
		;;
esac
