#!/bin/sh

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"

ctrlaltdel -s

mountpoint -q /proc                || mount -v -t proc proc /proc -o nosuid,noexec,nodev
mountpoint -q /sys                 || mount -v -t sysfs sys /sys -o nosuid,noexec,nodev
mountpoint -q /run                 || mount -v -t tmpfs run /run -o mode=0755,nosuid,nodev
mountpoint -q /dev                 || mount -v -t devtmpfs dev /dev -o mode=0755,nosuid
mkdir -v -p -m0755 /run/lvm /run/user /run/lock /run/log /dev/pts /dev/shm
mountpoint -q /dev/pts             || mount -v -t devpts devpts /dev/pts -o mode=0620,gid=5,nosuid,noexec
mountpoint -q /dev/shm             || mount -v -t tmpfs shm /dev/shm -o mode=1777,nosuid,nodev
mountpoint -q /sys/kernel/security || mount -v -n -t securityfs securityfs /sys/kernel/security
mountpoint -q /sys/fs/cgroup       || mount -v -o mode=0755 -t tmpfs cgroup /sys/fs/cgroup

live="0"
for arg in $(cat /proc/cmdline);do
	case "$arg" in
		live=*)     live="${arg#*=}" ;;
	esac
done

udevd --daemon
udevadm trigger --action=add --type=subsystems
udevadm trigger --action=add --type=devices
udevadm trigger --action=change --type=devices
udevadm settle

if [ -x /etc/rc.modules ]; then
	/etc/rc.modules
fi

mount -v -o remount,ro /

if [ "$live" != "1" ]; then
	if [ -x /usr/bin/mdadm -o -f /etc/mdadm/mdadm.conf ]; then
		mdadm -As
	fi

	if [ -x /usr/bin/vgchange ]; then
		modprobe dm-mod 2>/dev/null
		vgscan -v --mknodes --ignorelockingfailure >/dev/null
		vgchange -v --sysinit --activate y >/dev/null
	fi
fi

if [ -f /forcefsck ]; then
	FORCEFSCK="-f"
fi

fsck $FORCEFSCK -A -T -C -a -v
if [ $? -gt 1 ]; then
	echo
	echo "***************  FILESYSTEM CHECK FAILED  ******************"
	echo "*                                                          *"
	echo "*  Please repair manually and reboot. Note that the root   *"
	echo "*  file system is currently mounted read-only. To remount  *"
	echo "*  it read-write type: mount -n -o remount,rw /            *"
	echo "*  When you exit the maintainance shell the system will    *"
	echo "*  reboot automatically.                                   *"
	echo "*                                                          *"
	echo "************************************************************"
	echo
	sulogin -p
	umount -v -a -r
	mount -v -o remount,ro /
	reboot -f
	exit 0
fi

mount -v -o remount,rw /

swapon -v -a

mount -v -a -t "nosysfs,nonfs,nonfs4,nosmbfs,nocifs" -O no_netdev

cp /var/lib/random-seed /dev/urandom >/dev/null 2>&1 || true
( umask 077; bytes=$(cat /proc/sys/kernel/random/poolsize) || bytes=512; dd if=/dev/urandom of=/var/lib/random-seed count=1 bs=$bytes >/dev/null 2>&1 )

ifup -v -a

if [[ -f '/etc/hostname' ]]
then
	hostname -F /etc/hostname
fi

if [[ -f '/etc/timezone' ]]; then
	MYTZ="$(cat /etc/timezone)"
	if [ -n "$MYTZ" ]; then
		ln -sf /usr/share/zoneinfo/$MYTZ /etc/localtime
	fi
fi

hwclock -v --hctosys

sysctl -p /etc/sysctl.d/*.conf

if [[ -f '/etc/keymap' ]]; then
	MYKMAP="$(cat /etc/keymap)"
	if [ -n "$MYKMAP" ]; then
		loadkeys -v -q $MYKMAP
	else
		loadkeys -v -q us
	fi
fi

if [[ -f '/etc/font' ]]; then
	MYFONT="$(cat /etc/font)"
	if [ -n "$MYFONT" ]; then
		setfont -v $MYFONT
	fi
else
	setfont -v lat2-16 -m 8859-2
fi

install -v -m0664 -o root -g utmp /dev/null /run/utmp
if [ ! -e /var/log/wtmp ]; then
	install -v -m0664 -o root -g utmp /dev/null /var/log/wtmp
fi
if [ ! -e /var/log/btmp ]; then
	install -v -m0600 -o root -g utmp /dev/null /var/log/btmp
fi
install -v -dm1777 /tmp/.X11-unix /tmp/.ICE-unix
rm -f -v /etc/nologin /forcefsck /forcequotacheck /fastboot

dmesg >/var/log/dmesg.log

if [ -x /etc/rc.local ]; then
	/etc/rc.local
fi

dmesg -n 1

respawn runsvdir -P /var/service &
