#!/bin/sh
# https://github.com/leahneukirchen/sabotage/blob/master/KEEP/runsvdir-start
export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"
exec runsvdir -P /var/service 'log: ................................................................................................................................................................................................................................................................'
