#!/bin/sh
export PATH="/usr/local/games:/usr/local/sbin:/usr/local/bin:/usr/games:/usr/bin"

 . /etc/rc.conf


for arg in $(cat /proc/cmdline);do
	case "$arg" in
		keymap=*)      keymap="${arg#*=}" ;;
		fontname=*)    fontname="${arg#*=}" ;;
	esac
done

if [ -n "$keymap" ] ;then
	loadkeys $keymap
fi

if [ -n "$fontname" ] ;then
	setfont $fontname
fi

if [ "$IPTABLES" = "yes" ]; then
	/etc/rc.d/rc.iptables start
fi

if [ "$IP6TABLES" = "yes" ]; then
	/etc/rc.d/rc.ip6tables start
fi

if [ "$NFTABLES" = "yes" ]; then
	/etc/rc.d/rc.nftables start
fi

if [ "$IPSET" = "yes" ]; then
	/etc/rc.d/rc.ipset start
fi

if [ "$ALSA" = "yes" ]; then
	/etc/rc.d/rc.alsa start
fi

if [ -x /etc/rc.local ]; then
	/etc/rc.local
fi

exec runsvdir -P /var/service 'log: ................................................................................................................................................................................................................................................................'
