#!/bin/sh
export PATH="/usr/local/games:/usr/local/sbin:/usr/local/bin:/usr/games:/usr/bin"

 . /etc/rc.conf


for arg in $(cat /proc/cmdline);do
	case "$arg" in
		keymap=*)      keymap="${arg#*=}" ;;
		fontname=*)    fontname="${arg#*=}" ;;
	esac
done

if [ -n "$keymap" ] ;then
	loadkeys $keymap
fi

if [ -n "$fontname" ] ;then
	setfont $fontname
fi

if [ "$IPTABLES" = "yes" ]; then
	if [ -x "/etc/rc.d/rc.iptables" ]; then
		/etc/rc.d/rc.iptables start
	fi
fi

if [ "$IP6TABLES" = "yes" ]; then
	if [ -x "/etc/rc.d/rc.ip6tables" ]; then
		/etc/rc.d/rc.ip6tables start
	fi
fi

if [ "$NFTABLES" = "yes" ]; then
	if [ -x "/etc/rc.d/rc.nftables" ]; then
		/etc/rc.d/rc.nftables start
	fi
fi

if [ "$IPSET" = "yes" ]; then
	if [ -x "/etc/rc.d/rc.ipset" ]; then
		/etc/rc.d/rc.ipset start
	fi
fi

if [ "$ALSA" = "yes" ]; then
	if [ -x "/etc/rc.d/rc.alsa" ]; then
		/etc/rc.d/rc.alsa start
	fi
fi

if [ -x /etc/rc.local ]; then
	/etc/rc.local
fi

if [ -d "/var/service/" ]; then
	(
		cd /var/service/
		for i in * ; do
			cp -rf /etc/service/$i /run/service/
		done
	)
fi

exec env - PATH=$PATH \
 runsvdir -P /run/service 'log: ................................................................................................................................................................................................................................................................'
