#!/usr/bin/openrc-run
# Copyright (c) 2009-2015 Funtoo Technologies
# Released under the 2-clause BSD license.

description="Sets the hostname of the machine."

depend() {
	need root
}

start()
{
	hostname=${hostname-${HOSTNAME-localhost}}
	out=$hostname
	short=${hostname%%.*}
	if [ "$short" != "$hostname" ]; then
		out="$out $short"
	fi
	[ "$RC_SYS" = "LXC" ] && return 0
	ebegin "Setting hostname to $hostname"
	hostname "$short"
	eend $? "Failed to set the hostname"
}
