#!/bin/bash

set -e

unpck() {
	echo "Unpacking tarball: $tarball..."
	case $tarball in
		*.tar*|*.tgz|*.tbz|*.tbz2|*.tlz|*.txz)
			tar -xf $tarball
			;;
		*.zip|*.xpi)
			unzip -o $tarball
			;;
		*.7z)
			7zr x $tarbal
			;;
		*.Z|*.z)
			uncompress -c $tarball | tar -xf -
			;;
		*.rpm)
			rpm2cpio $tarball | cpio -idm --quiet
			;;
		*)
			cp $tarball $SOURCES
	esac
}

ftch() {
	echo "Fetching and extracting $name sources..."
	case $fetchurl in
		git://*)
			echo "Cloning git repository: $fetchurl"
			cd $SOURCES
			git clone $fetchurl $gitopts
			;;
		ftp://*|http://*|https://*)
			echo "Fetching $fetchurl"
			cd $SOURCES
			wget -c $fetchurl
			unpck
	esac
}

check_for_fetch() {
	if [ -n "$fetchurl" ]; then
		ftch
	fi
}

applypatch() {
	echo "Applying patch $@..."
	patch -Np1 -i $@
}

strp() {
	echo "Stripping package $name..."
	find $ROOTFS -type f | xargs file 2>/dev/null | grep "LSB executable"       | cut -f 1 -d : | xargs $STRIP --strip-all	2>/dev/null || true
	find $ROOTFS -type f | xargs file 2>/dev/null | grep "shared object"        | cut -f 1 -d : | xargs $STRIP --strip-unneeded	2>/dev/null || true
	find $ROOTFS -type f | xargs file 2>/dev/null | grep "current ar archive"   | cut -f 1 -d : | xargs $STRIP --strip-debug	2>/dev/null || true
	find $ROOTFS -type f | xargs file 2>/dev/null | grep "libtool library file" | cut -f 1 -d : | xargs rm -rf			2>/dev/null || true
	cd $ROOTFS
	rm -rf usr/{,local/}{,share/}{doc,man,misc,info,locale} usr{,/local}{,/share},opt/*}/{man,info} usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc}
}

strptc() {
	echo "Stripping package $name..."
	find $TOOLS -type f | xargs file 2>/dev/null | grep "LSB executable"       | cut -f 1 -d : | xargs strip --strip-all	2>/dev/null || true
	find $TOOLS -type f | xargs file 2>/dev/null | grep "shared object"        | cut -f 1 -d : | xargs strip --strip-unneeded	2>/dev/null || true
	find $TOOLS -type f | xargs file 2>/dev/null | grep "current ar archive"   | cut -f 1 -d : | xargs strip --strip-debug	2>/dev/null || true
}

. $1

case $MODE in
	toolchain)
		check_for_fetch
		bld
		strptc
		;;
	*)
		check_for_fetch
		bld
		strp
esac

