#!/usr/bin/env bash

main() {
	if [ -z "$LINUX" ]; then
		LINUX="linux"
	fi

	case $BARCH in
		x86_64|i686|aarch64|armv7hl|armv6hl)
				EXTRAPKG="gnu-efi"
				;;
	esac

	IMAGEFS="$BUILD/imagefs"

	rm -rf "$IMAGEFS"
	mkdir -p "$IMAGEFS"

	IMG="$BUILD/ataraxialinux-$BARCH.img"
	dd if=/dev/zero of=$IMG bs=1 count=0 seek=4G
	losetup -f $IMG
	lodev=$(losetup -a | grep "$IMG" | cut -d: -f1)

	case $BARCH in
		x86_64|i686)
			parted -s $lodev mklabel msdos
			parted -a optimal -s $lodev mkpart primary 0% 100%
			parted -s $lodev set 1 boot on
			;;
		*)
			parted -s $lodev mklabel msdos
			parted -a optimal -s $lodev mkpart primary 0% 100%
			;;
	esac

	lopart="${lodev}p1"
	yes | mkfs.ext4 $lopart

	mount -o loop $lopart "$IMAGEFS"

	packages="base-files netbase linux-headers musl tzdata man-pages musl-tools gettext-tiny \
		zlib xz lz4 zstd bzip2 file ncurses readline m4 bison flex bc gmp mpfr mpc binutils gcc \
		ccache pkgconf pcre libcap-ng cracklib pam libpwquality attr acl libcap shadow grep sed psmisc \
		mksh bash slibtool inetutils net-tools gdbm db sqlite expat libffi libressl nettle python perl \
		ca-certificates autoconf automake lzip libarchive lzo kmod libuargp libelf gawk findutils 9base \
		lobase sbase ubase less mandoc gzip ncompress libmnl libnftnl libnfnetlink libnetfilter_conntrack \
		libnl libpcap iptables iproute2 kbd samurai python-setuptools meson make patch tar cpio nano $EXTRAPKG \
		procps-ng gperf libseccomp util-linux libaio lvm2 popt json-c argon2 cryptsetup systemd dbus \
		e2fsprogs btrfs-progs hwids run-parts libssh2 nghttp2 heimdal curl popt rpm neko $LINUX"

	neko em -c "$BUILD"/target.config -m "$BUILD"/mask -r "$IMAGEFS" -wdts $packages

	umount -l "$IMAGEFS"
	losetup -d $lodev
}
