#!/bin/bash

main() {
	if [ -z "$LINUX" ]; then
		LINUX="linux"
	fi

	IMAGEFS="$BUILD/imagefs"

	rm -rf "$IMAGEFS"
	mkdir -p "$IMAGEFS"

	IMG="$BUILD/ataraxialinux-$BARCH.img"
	dd if=/dev/zero of=$IMG bs=1 count=0 seek=4G
	losetup -f $IMG
	lodev=$(losetup -a | grep "$IMG" | cut -d: -f1)

	case $BARCH in
		x86_64|i686)
			parted -s $lodev mklabel msdos
			parted -a optimal -s $lodev mkpart primary 0% 100%
			parted -s $lodev set 1 boot on
			;;
		*)
			parted -s $lodev mklabel msdos
			parted -a optimal -s $lodev mkpart primary 0% 100%
			;;
	esac

	lopart="${lodev}p1"
	yes | mkfs.ext4 $lopart

	mount -o loop $lopart "$IMAGEFS"

	packages="base-files netbase linux-headers musl tzdata man-pages musl-tools gettext-tiny \
			zlib xz lz4 zstd bzip2 file ncurses readline m4 bison flex bc gmp mpfr mpc binutils gcc \
			ccache pkgconf libsepol libselinux libsemanage cracklib pam libpwquality attr acl libcap shadow \
			pcre grep mksh bash slibtool gdbm db expat perl libressl nettle ca-certificates autoconf automake \
			lzip libarchive lzo kmod libuargp libelf coreutils mawk openbsd-diffutils ubase sinit netbsd-tools toybox \
			less mandoc dialog pigz iproute2 kbd make vim libcap-ng util-linux e2fsprogs btrfs-progs heimdal hwids \
			gperf eudev openrc ifupdown dhcp libssh2 nghttp2 curl lua popt rpm neko $LINUX"

	neko em -c "$BUILD"/target.config -m "$BUILD"/mask -r "$IMAGEFS" -wd $packages

	umount -l "$IMAGEFS"
	losetup -d $lodev
}
