#!/bin/bash

generate_initramfs() {
	packages="base-files linux-api-headers musl tzdata man-pages musl-tools zlib file ncurses readline bzip2 attr acl \
		libcap pcre grep mksh bash expat libressl ca-certificates xz lzip lz4 zstd kmod busybox dialog pigz libmnl libnftnl \
		libnfnetlink libnetfilter_conntrack libnl libpcap iptables iproute2 kbd tar vim libcap-ng util-linux e2fsprogs libaal \
		reiser4progs dosfstools hwids eudev linux dpkg dhcpcd wireless_tools wpa_supplicant popt gptfdisk \
		libssh2 c-ares libev nghttp2 curl"

	ne -c "$BUILD"/target.config -r "$INITRAMFS" -EWnd $packages

	pushd "$INITRAMFS"
		ln -sf usr/bin/init init

		rm -rf usr/include
		rm -rf usr/share/man
		rm -rf usr/share/doc
		rm -rf usr/share/info

		find . -name "*.a" -print0 | xargs -0 rm -rf
		find . -name "*.h" -print0 | xargs -0 rm -rf
		find . -name "*.hpp" -print0 | xargs -0 rm -rf
		find . -name "*.pc" -print0 | xargs -0 rm -r

		mv boot/vmlinuz-linux "$ISODIR"/seiba/seiba

		cp "$TOOLS"/$XTARGET/lib/*.so* usr/lib/

		find . | cpio -H newc -o | zstd -12 > "$ISODIR"/seiba/seiba.zst
	popd
}

make_iso_x86() {
	mkdir -p "$ISODIR"/boot/grub "$ISODIR"/boot/isolinux "$ISODIR"/efi/boot

	grub_mod="all_video disk part_gpt part_msdos linux normal configfile search search_label efi_gop fat iso9660 cat echo ls test true help gzio multiboot2 efi_uga"

	case $BARCH in
		amd64)
			format="x86_64-efi"
			efi="bootx64.efi"
			;;
		i386)
			format="i386-efi"
			efi="bootia32.efi"
			;;
	esac

cat << CEOF > "$GRUBEFICFG"
search --no-floppy --set=root --label "ataraxialinux"
set prefix=(\$root)/boot/grub
CEOF

cat << CEOF > "$ISODIR"/boot/grub/grub.cfg
menuentry "Ataraxia Linux" {
linux	/seiba/seiba live=1 nofsck rw
initrd	/seiba/seiba.zst
}
CEOF

	grub-mkimage \
		--config="$GRUBEFICFG" \
		--prefix="/boot/grub" \
		--output="$ISODIR"/efi/boot/$efi \
		--format="$format" \
		--compress="xz" \
		$grub_mod

	mformat -i "$ISODIR"/boot/grub/efi.img -C -f 1440 ::
	mcopy -i "$ISODIR"/boot/grub/efi.img -s "$ISODIR"/efi ::

	cp -a "$STUFF"/mklive/isolinux.bin "$ISODIR"/boot/isolinux
	cp -a "$STUFF"/mklive/ldlinux.c32 "$ISODIR"/boot/isolinux
	cp -a "$STUFF"/mklive/libcom32.c32 "$ISODIR"/boot/isolinux
	cp -a "$STUFF"/mklive/vesamenu.c32 "$ISODIR"/boot/isolinux
	cp -a "$STUFF"/mklive/libutil.c32 "$ISODIR"/boot/isolinux
	cp -a "$STUFF"/mklive/chain.c32 "$ISODIR"/boot/isolinux
	cp -a "$STUFF"/mklive/background.png "$ISODIR"/boot/isolinux/background.png

cat << CEOF > "$ISODIR"/boot/isolinux/isolinux.cfg
UI vesamenu.c32
PROMPT 0
TIMEOUT 100
ONTIMEOUT ataraxialinux
MENU TABMSG Press ENTER to boot or TAB to edit a menu entry
MENU AUTOBOOT BIOS default device boot in # second{,s}...
MENU BACKGROUND /boot/isolinux/background.png
MENU WIDTH 78
MENU MARGIN 1
MENU ROWS 4
MENU VSHIFT 2
MENU TIMEOUTROW 8
MENU TABMSGROW 2
MENU CMDLINEROW 11
MENU HELPMSGROW 16
MENU HELPMSGENDROW 29
MENU COLOR title        * #9000FF *
MENU COLOR border       * #00000000 #00000000 none
MENU COLOR sel          * #ffffffff #9000FF *
LABEL ataraxialinux
MENU LABEL Ataraxia Linux
KERNEL /seiba/seiba live=1 nofsck rw
APPEND initrd=/seiba/seiba.zst
CEOF

	xorriso -as mkisofs \
		-isohybrid-mbr "$STUFF"/mklive/isohdpfx.bin \
		-iso-level 2 \
		-c boot/isolinux/boot.cat \
		-b boot/isolinux/isolinux.bin \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		-eltorito-alt-boot \
		-e boot/grub/efi.img \
		-no-emul-boot \
		-isohybrid-gpt-basdat \
		-A 'ataraxialinux' -V 'ataraxialinux' \
		-o "$BUILD"/ataraxialinux-$BARCH.iso \
		"$ISODIR"/
}

main() {
	ISODIR="$BUILD/rootcd"
	INITRAMFS="$BUILD/initramfs"
	GRUBEFICFG="$BUILD/efi.cfg"

	rm -rf "$ISODIR" "$INITRAMFS" "$GRUBEFICFG"
	mkdir -p "$ISODIR/seiba" "$INITRAMFS"

	generate_initramfs

	case $BARCH in
		amd64|i386)
			make_iso_x86
			;;
	esac
}
