#!/usr/bin/env bash

main() {
	if [ -z "$LINUX" ]; then
		LINUX="linux"
	fi

	STAGE="$BUILD/stage"

	rm -rf "$STAGE"
	mkdir -p "$STAGE"

	packages="base-files netbase linux-headers musl tzdata man-pages musl-tools gettext-tiny \
		zlib xz lz4 zstd bzip2 file ncurses readline m4 bison flex bc gmp mpfr mpc binutils gcc \
		pkgconf pcre libcap-ng cracklib libtirpc pam attr acl libcap shadow grep sed psmisc mksh bash \
		slibtool net-tools gdbm db53 sqlite expat libffi libressl nettle python perl ca-certificates \
		autoconf automake lzip libarchive lzo kmod libuargp libelf libpwquality gawk findutils 9base \
		lobase sbase ubase less mandoc gzip ncompress libmnl libnftnl libnfnetlink libnetfilter_conntrack \
		libnl libpcap iptables iproute2 kbd samurai python-setuptools meson make patch tar cpio nano iputils \
		procps-ng gperf libseccomp util-linux libaio lvm2 popt json-c argon2 cryptsetup hwids systemd \
		dbus-broker dbus e2fsprogs btrfs-progs run-parts libssh2 nghttp2 c-ares heimdal curl rpm neko $LINUX"

	neko em -c "$BUILD"/target.config -m "$BUILD"/mask -r "$STAGE" -wdt $packages

	pushd "$STAGE"
		bsdtar -c --zstd -f "$BUILD"/ataraxialinux-$BARCH.tar.zst .
	popd
}
