#!/bin/bash
#
# Written by Ishimoto Shinobu
#
# Also thanks Void linux for required code!
#

umask 022
unalias -a

msg() {
	local msg=$(echo $1 | tr -s / /)
	printf "$msg\n"
}

check_updates() {
	mypkg="$1"

	source $mypkg/Pkgfile

	homepage="$(grep "^# URL[[:blank:]]*:" $mypkg/Pkgfile | sed 's/^# URL[[:blank:]]*:[[:blank:]]*//' | tr ' ' '\n' | awk '!a[$0]++')"
	distfiles="${source[@]}"

	local i p url sfname lpname bbname githubname rx found_version consider
	local update_override=$mypkg/update
	local original_pkgname=$name
	local urlpfx urlsfx

	if [ -r $update_override ]; then
		. $update_override
	fi

	if ! type curl >/dev/null 2>&1; then
		echo "ERROR: cannot find \`curl' executable!"
		return 1
	fi

	export LC_ALL=C

	if [ -z "$site" ]; then
		printf '%s\n' "$homepage"
		for i in $distfiles; do
			printf '%s\n' "${i%/*}/"
		done
	else
		printf '%s\n' "$site"
	fi |
	while IFS= read -r url; do
		printf '%s\n' "$url"
		if [ "$single_directory" ]; then
			continue
		fi
		rx=
		urlpfx="${url}"
		urlsfx=
		dirpfx=
		case "$url" in
			  *sourceforge.net/sourceforge*|\
			  *code.google.com*|*googlecode*|\
			  *launchpad.net*|\
			  *cpan.*|\
			  *pythonhosted.org*|\
			  *github.com*|\
			  *gitlab.com*|*gitlab.gnome.org*|*gitlab.freedesktop.org*|\
			  *bitbucket.org*|\
			  *ftp.gnome.org*|\
			  *kernel.org/pub/linux/kernel/*|\
			  *cran.r-project.org/src/contrib*|\
			  *rubygems.org*)
				continue
				;;
			*)
				vdpfx=${vdprefix:-"|v|\\Q$name\\E"}
				vdsfx=${vdsuffix:-"|\\.x"}
				match=$(grep -Po "^[^/]+//[^/]+(/.+)?/($vdpfx)(?=[-_.0-9]*[0-9](?<!\\Q$name\\E)($vdsfx)/)" <<< "$url")
				if [ "$?" = 0 ]; then
					urlpfx="${match%/*}/"
					dirpfx="${match##*/}"
					urlsfx="${url#$urlpfx}"
					urlsfx="${urlsfx#*/}"
					rx="href=[\"']?(\\Q$urlpfx\\E)?\\.?/?\\K\\Q$dirpfx\\E[-_.0-9]*[0-9]($vdsfx)[\"'/]"
				fi
				;;
		esac
		if [ "$rx" ]; then
			skipdirs=
			curl --max-time 10 -Lsk "$urlpfx" |
				grep -Po -i "$rx" | sort -Vru |
				while IFS= read -r newver; do
					newurl="${urlpfx}${newver}${urlsfx}"
					if [ "$newurl" = "$url" ]; then
						skipdirs=yes
					fi
					if [ -z "$skipdirs" ]; then
						printf '%s\n' "$newurl"
					fi
				done
		fi
	done |
	while IFS= read -r url; do
		rx=
		if [ -z "$site" ]; then
			case "$url" in
			*sourceforge.net/sourceforge*)
				sfname="$(printf %s "$url" | cut -d/ -f5)"
				url="https://sourceforge.net/projects/$sfname/rss?limit=200";;
			*code.google.com*|*googlecode*)
				url="http://code.google.com/p/$name/downloads/list";;
			*launchpad.net*)
				lpname="$(printf %s "$url" | cut -d/ -f4)"
				url="https://launchpad.net/$lpname/+download";;
			*cpan.*)
				pkgname=${pkgname#perl-};;
			*pythonhosted.org*)
				pkgname=${pkgname#python-}
				pkgname=${pkgname#python3-}
				url="https://pypi.org/simple/$name";;
			*github.com*)
				githubname="$(printf %s "$url" | cut -d/ -f4,5)"
				url="https://github.com/$githubname/tags"
				rx='/archive/(v?|\Q'"$name"'\E-)?\K[\d\.]+(?=\.tar\.gz")';;
			*gitlab.com*|*gitlab.gnome.org*|*gitlab.freedesktop.org*)
				gitlaburl="$(printf %s "$url" | cut -d/ -f1-5)"
				url="$gitlaburl/tags"
				rx='/archive/[^/]+/\Q'"$name"'\E-v?\K[\d\.]+(?=\.tar\.gz")';;
			*bitbucket.org*)
				bbname="$(printf %s "$url" | cut -d/ -f4,5)"
				url="https://bitbucket.org/$bbname/downloads"
				rx='/(get|downloads)/(v?|\Q'"$name"'\E-)?\K[\d\.]+(?=\.tar)';;
			*ftp.gnome.org*)
				: ${pattern="\Q$name\E-\K[0-9]+\.[0-9]*[02468]\.[0-9.]*[0-9](?=)"}
				url="http://ftp.gnome.org/pub/GNOME/sources/$name/cache.json";;
			*kernel.org/pub/linux/kernel/*)
				rx=linux-'\K'${version%.*}'[\d.]+(?=\.tar\.xz)';;
			*cran.r-project.org/src/contrib*)
				rx='\b\Q'"${pkgname#R-cran-}"'\E_\K\d+(\.\d+)*(-\d+)?(?=\.tar)';;
			*rubygems.org*)
				url="https://rubygems.org/gems/${pkgname#ruby-}"
				rx='href="/gems/'${pkgname#ruby-}'/versions/\K[\d\.]*(?=")' ;;
			*crates.io*)
				url="https://crates.io/api/v1/crates/${pkgname#rust-}"
				rx='/crates/'${pkgname#rust-}'/\K[0-9.]*(?=/download)' ;;
			esac
		fi

		rx=${pattern:-$rx}
		rx=${rx:-'(?<!-)\b\Q'"$name"'\E[-_]?((src|source)[-_])?\K([^-/_\s]*?\d[^-/_\s]*?)(?=(?:[-_.](?:src|source|orig))?\.(?:[jt]ar|shar|t[bglx]z|tbz2|zip))\b'}
		curl -H 'Accept: text/html,application/xhtml+xml,application/xml,text/plain,application/rss+xml' --max-time 10 -Lsk "$url" |
			grep -Po -i "$rx"
	done |
	tr _ . |
	sort -Vu |
	while IFS= read -r found_version; do
		consider=true
		p="$ignore "
		while [ -n "$p" ]; do
			i=${p%% *}
			p=${p#* }
			case "$found_version" in
			$i)
				consider=false
			esac
		done
		if $consider; then
			vercmp "$original_pkgname-${version}_1" "$original_pkgname-$(printf %s "$found_version" | tr - .)_1"
			if [ $? = 255 ]; then
				msg "Update  ${original_pkgname} to ${found_version}"
			fi
		fi
	done
}

check_updates $1

exit 0
