#!/bin/bash
#
# Written by Ishimoto Shinobu
#
# Also thanks Void Linux and nemasu for required code!
#

check_updates() {
	echo "REWRITE ME!"
}

for packages in $(ls $REPO/); do
	case $packages in
		run-parts|ifupdown|base-files|sbase|ubase|sinit|autoconf2.13|musl-tools|mkinitrd)
			true
			;;
		*)
			check_updates $REPO/$packages
			;;
	esac
done

exit 0
