#!/usr/bin/sh
if [ -d "/run/service/dbus" ]; then
	sv check &>/dev/null /run/service/dbus || sv up /run/service/dbus
else
	rm -rf /run/service/bluetooth-mesh
fi
exec /usr/lib/bluetooth/bluetooth-meshd --nodetach
