#!/usr/bin/sh
if [ -d "/run/service/dbus" ]; then
	sv check /run/service/dbus || sv up /run/service/dbus
else
	rm -rf /run/service/elogind
fi
[ ! -d "/run/systemd" ] && mkdir -p /run/systemd
exec /usr/lib/elogind/elogind
