#!/usr/bin/sh
if [ -d "/run/service/elogind" ]; then
	sv check /run/service/elogind || sv up /run/service/elogind
else
	rm -rf /run/service/lightdm
fi
[ ! -d "/run/lightdm" ] && install -d -m0711 -olightdm -glightdm /run/lightdm
exec lightdm
