#!/bin/sh
sv check /run/service/statd >/dev/null || exit 1
if [ -e ./conf ]; then
	. ./conf
fi
if ! mountpoint -q /var/lib/nfs/rpc_pipefs; then
	mount -t rpc_pipefs rpc_pipefs /var/lib/nfs/rpc_pipefs -o defaults || exit 1
fi
if ! mountpoint -q /proc/fs/nfsd; then
	mount -t nfsd nfsd /proc/fs/nfsd || exit 1
fi
exportfs -ra > /dev/null || exit 1
rpc.nfsd -- ${PROCESSES:=4} || exit 1
sm-notify
exec rpc.mountd --foreground
