#!/usr/bin/sh
[ ! -d "/run/postgresql" ] && install -dm755 -o postgres -g postgres /run/postgresql
postgresql-check-db-dir /var/lib/postgres/data || rm -rf /run/service/postgresql
exec postgres -D /var/lib/postgres/data
