#!/bin/sh

printmsg() {
	local msg=$(echo $1 | tr -s / /)
	printf "\e[1m\e[32m==>\e[0m $msg\n"
	sleep 1
}

printmsgerror() {
	local msg=$(echo $1 | tr -s / /)
	printf "\e[1m\e[31m==!\e[0m $msg\n"
	sleep 1
	exit 1
}

check_for_root() {
	if [[ $EUID -ne 0 ]]; then
		printmsgerror "This script must be run as root" 
	fi
}

reposync() {
	printmsg "Syncing with januslinux repositories"
	if [ ! -d "/var/cache/ports" ]; then
		git clone https://github.com/JanusLinux/janus.git --depth 1 /var/cache/ports
	else
		cd /var/cache/ports && git pull
	fi
}

check_for_root
reposync

exit 0

