#!/bin/sh

printmsg() {
	local msg=$(echo $1 | tr -s / /)
	printf "\e[1m\e[32m==>\e[0m $msg\n"
	sleep 1
}

printmsgerror() {
	local msg=$(echo $1 | tr -s / /)
	printf "\e[1m\e[31m==!\e[0m $msg\n"
	sleep 1
	exit 1
}

check_for_root() {
	if [[ $EUID -ne 0 ]]; then
		printmsgerror "This script must be run as root" 
	fi
}

reposync() {
	printmsg "Syncing with januslinux repositories"
	cd /var/cache
	rm -rf master.tar.gz ports
	curl -C - -L -O https://github.com/ataraxialinux/ataraxia/archive/master.tar.gz
	tar -xf master.tar.gz
	mv ataraxia-master ports
	rm -rf master.tar.gz
}

check_for_root
reposync

exit 0

