#!/bin/sh -e

unset CROSS_COMPILE CC CXX AR AS RANLIB LD STRIP OBJCOPY OBJDUMP SIZE

if [ "$CFLAGS" ]; then
        export CFLAGS="$CFLAGS -ffat-lto-objects"
else
        export CFLAGS="-ffat-lto-objects"
fi
if [ "$CXXFLAGS" ]; then
        export CXXFLAGS="$CFLAGS -ffat-lto-objects"
else
    	export CXXFLAGS="-ffat-lto-objects"
fi

exec meson setup \
	--prefix        /usr \
	--libdir        lib \
	--libexecdir    lib \
	--sbindir       bin \
	--wrap-mode     nodownload \
	--cross-file	crossfile \
	-Dbuildtype=plain \
	-Db_lto=true \
	-Db_pie=true \
	"$@"
