#!/usr/bin/sh -e

exec meson setup \
	--prefix        /usr \
	--libdir        lib \
	--libexecdir    lib \
	--sbindir       bin \
	--wrap-mode     nodownload \
	-Dbuildtype=plain \
	-Db_lto=true \
	-Db_pie=true \
	"$@"
