#!/bin/sh -ex

exec meson setup \
  --prefix        /usr \
  --libexecdir    lib \
  --sbindir       bin \
  --wrap-mode     nodownload \
  -Dbuildtype=release \
  -Db_lto=true \
  -Db_pie=true \
  "$@"
