#!/bin/bash

printmsg() {
	local msg=$(echo $1 | tr -s / /)
	printf "\e[1m\e[32m==>\e[0m $msg\n"
	sleep 1
}

printmsgerror() {
	local msg=$(echo $1 | tr -s / /)
	printf "\e[1m\e[31m==!\e[0m $msg\n"
	sleep 1
	exit 1
}

pkginstall() {
	local pkg="$@"
	for mergepkg in $pkg; do
		printmsg "Building and installing $mergepkg"
		cd $REPO/$mergepkg
		pkgmk -d -if -im -is -cf /etc/pkgmk.conf
		pkgadd $PKGSDIR/$mergepkg#*.pkg.tar.xz
	done
}

buildonlt() {
	local pkg="$@"
	for mergepkg in $pkg; do
		printmsg "Building $mergepkg"
		cd $REPO/$mergepkg
		pkgmk -d -if -im -is -cf /etc/pkgmk.conf
	done
}

installonly() {
	local pkg="$@"
	for mergepkg in $pkg; do
		printmsg "Installing $mergepkg"
		pkgadd $PKGSDIR/$mergepkg#*.pkg.tar.xz
	done
}

setup_environment() {
	export PATH="/usr/bin:/busybox/bin"

	export OUTDIR="/output"
	export PKGSDIR="$OUTDIR/packages"
	export REPO="/usr/janus/packages"
}

setup_environment

exit 0

