#! /bin/bash
# Script originated here:
# http://www.linuxfromscratch.org/lfs/view/development/chapter06/bc.html
sed -e '1   s/^/{"/' \
    -e     's/$/",/' \
    -e '2,$ s/^/"/'  \
    -e   '$ d'       \
    -i libmath.h

sed -e '$ s/$/0}/' \
    -i libmath.h
