#!/bin/sh

export PATH="/usr/bin:/usr/local/bin"

dmesg -n 1

echo Mounting virtual filesystems...
mount -t proc none /proc
mount -t sysfs none /sys

echo Starting mdev hotplug...
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

echo Mounting root read-only...
mount -o remount,ro /

echo Checking filesystems...
fsck -ATa
if [ $? -eq 1 ]; then
	echo Filesystem errors exist, fix manually.
	sh
	halt -r
fi

echo Remounting root as read-write...
mount -o remount,rw /

echo Activating swap partition...
swapon -a

echo Mounting filesystems...
mount -a

echo Cleaning misc files...
: > /var/run/utmp
rm -rf /forcefsck /fastboot /etc/nologin /etc/shutdownpid
(cd /var/run && find . -name "*.pid" -delete)
(cd /var/lock && find . ! -type d -delete)
(cd /tmp && find . ! -name . -delete)
mkdir -m 1777 /tmp/.ICE-unix

echo Set up kernel variables...
sysctl -p

echo Setting hostname to $(cat /etc/hostname)...
hostname $(cat /etc/hostname)

echo Synchronizing clock...
hwclock -u -s

echo Setting up networking...
for DEVICE in /sys/class/net/* ; do
	ip link set ${DEVICE##*/} up
	[ ${DEVICE##*/} = wlan0 ] && wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf
	[ ${DEVICE##*/} != lo ] && [ ${DEVICE##*/} != sit0 ] && udhcpc -b -i ${DEVICE##*/} -s /etc/init.d/rc.dhcp
done

echo Saving boot messages...
dmesg >> /var/log/dmesg.log

echo Welcome to your box!
