#!/bin/sh

export PATH="/usr/bin:/usr/local/bin"

dmesg -n 1

echo Mounting virtual filesystems...
mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs /tmp /tmp
mkdir /dev/pts
mkdir /dev/shm
mount -t devpts none /dev/pts
mount -t tmpfs none /dev/shm

echo Starting mdev hotplug...
echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

echo Mounting root read-only...
mount -o remount,ro /

echo Checking filesystems...
fsck -A -T -C -a
if [ $? -gt 1 ]; then
	echo
	echo "***************  FILESYSTEM CHECK FAILED  ******************"
	echo "*                                                          *"
	echo "*  Please repair manually and reboot. Note that the root   *"
	echo "*  file system is currently mounted read-only. To remount  *"
	echo "*  it read-write type: mount -n -o remount,rw /            *"
	echo "*  When you exit the maintainance shell the system will    *"
	echo "*  reboot automatically.                                   *"
	echo "*                                                          *"
	echo "************************************************************"
	echo
	sulogin -p
	echo "Automatic reboot in progress..."
	umount -a -r
	mount -o remount,ro /
	reboot -f
	exit 0
fi

echo Remounting root as read-write...
mount -o remount,rw /

echo Activating swap partition...
swapon -a

echo Mounting filesystems...
mount -a

echo Cleaning misc files...
: > /var/run/utmp
rm -rf /forcefsck /fastboot /etc/nologin /etc/shutdownpid
(cd /var/run && find . -name "*.pid" -delete)
(cd /var/lock && find . ! -type d -delete)
(cd /tmp && find . ! -name . -delete)
mkdir -m 1777 /tmp/.ICE-unix

echo Set up kernel variables...
sysctl -p

echo Setting hostname to $(cat /etc/hostname)...
hostname $(cat /etc/hostname)

echo Synchronizing clock...
hwclock -u -s

echo Setting up networking...
for DEVICE in /sys/class/net/* ; do
	ip link set ${DEVICE##*/} up
	[ ${DEVICE##*/} = wlan0 ] && wpa_supplicant -B -iwlan0 -c/etc/wpa_supplicant.conf
	[ ${DEVICE##*/} != lo ] && [ ${DEVICE##*/} != sit0 ] && udhcpc -b -i ${DEVICE##*/} -s /etc/init.d/rc.dhcp
done

echo Saving boot messages...
dmesg >> /var/log/dmesg.log

echo Welcome to your box!
