#!/bin/sh

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin"

dmesg -n 1

mount -t proc none /proc
mount -t sysfs none /sys
mount -t tmpfs none /tmp -o mode=1777
mount -t devtmpfs none /dev
mkdir -p /dev/pts
mount -t devpts none /dev/pts

echo /sbin/mdev > /proc/sys/kernel/hotplug
mdev -s

export PID1_SHELL=true

echo "Welcome to januslinux recovery shell!"

exec setsid cttyhack ash
