#!/bin/sh

VER=20180729

printver() {
cat <<EOF
reposync - Simple tool is intended for repositories synchronization. Made for januslinux.

Version installed: $VER

Copyright 2017-2018 januslinux Inc. This software is licensed under "MIT" license.

EOF
	exit 0
}

printmsg() {
	local msg=$(echo $1 | tr -s / /)
	printf "\e[1m\e[32m==>\e[0m $msg\n"
	sleep 1
}

printmsgerror() {
	local msg=$(echo $1 | tr -s / /)
	printf "\e[1m\e[31m==!\e[0m $msg\n"
	sleep 1
	exit 1
}

check_for_root() {
	if [[ $EUID -ne 0 ]]; then
		printmsgerror "This script must be run as root"
	fi
}

reposync_main() {
	printmsg "Syncing with 'main' repository"
	if [ ! -d "/usr/janus" ]; then
		git clone https://github.com/JanusLinux/janus.git --depth 1 /usr/janus
	else
		cd /usr/janus && git pull
	fi
}

reposync_extra() {
	printmsg "Syncing with 'extra' repository"
	if [ ! -d "/usr/janus/extra" ]; then
		git clone https://github.com/JanusLinux/extra.git --depth 1 /usr/janus/extra
	else
		cd /usr/janus/extra && git pull
	fi
}

reposync_multilib() {
	printmsg "Syncing with 'multilib' repository"
	if [ ! -d "/usr/janus/multilib" ]; then
		git clone https://github.com/JanusLinux/multilib.git --depth 1 /usr/janus/multilib
	else
		cd /usr/janus/multilib && git pull
	fi
}

reposync_extra_multilib() {
	printmsg "Syncing with 'extra-multilib' repository"
	if [ ! -d "/usr/janus/extra-multilib" ]; then
		git clone https://github.com/JanusLinux/extra-multilib.git --depth 1 /usr/janus/extra-multilib
	else
		cd /usr/janus/extra-multilib && git pull
	fi
}

case $1 in
	version|v|ver|-v|--v)
		printver
		;;
	multilib|ml|-ml|--ml)
		check_for_root
		reposync_multilib
		;;
	extra|e|-e|--e)
		check_for_root
		reposync_extra
		;;
	extra-multilib|eml|-eml|--eml)
		check_for_root
		reposync_extra_multilib
		;;
	all|a|-a|-all)
		check_for_root
		reposync_main
		reposync_extra
		reposync_multilib
		reposync_extra_multilib
		;;
	*|main|m|-m|--m)
		check_for_root
		reposync_main
esac

exit 0

