#!/bin/sh

usage() {
cat <<EOF

service - the service management utility.

Usage: service [one of following option] [available service]

	start       Start a service
	stop        Stop a running service
	restart     Stop, then start a previously running service
	status      Report the status of the given service
	add         Adds a service
	remove      Removes a service
	init        Start all services
	shutdown    Stop all services

EOF
	exit 0
}

case "$1" in
	start)
		sv up /etc/service/$2
		;;
	stop)
		sv down /etc/service/$2
		;;
	restart)
		sv down /etc/service/$2
		sleep 1
		sv up /etc/service/$2
		;;
	status)
		sv status /etc/service/$2
		;;
	add)
		ln -sf /var/service/$2 /etc/service/$2
		;;
	remove)
		rm -rf /etc/service/$2
		;;
	init)
		sv up /etc/service/*
		;;
	shutdown)
		sv down /etc/service/*
		;;
	usage|*)
		usage
esac

exit 0

